# -*- coding: utf-8 -*-
"""Exercícios Módulo 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fPXuUS-NeoH8ABii8q2EKRU5LPdlGuA

# Exercícios do Módulo 1 - Operações, Variáveis e Input

### Parte 1 - Operações e Variáveis
Crie um programa que imprima (print) os principais indicadores da loja Hashtag&Drink no último ano.
Obs: faça tudo usando variáveis.

Valores do último ano:

Quantidade de Vendas de Coca = 150<br>
Quantidade de Vendas de Pepsi = 130<br>
Preço Unitário da Coca = 1,50 <br>
Preço Unitário da Pepsi = 1,50<br>
Custo da Loja: 2.500,00

Use o bloco abaixo para criar todas as variáveis que precisar.
"""
def parte1():
    qtd_vendas_coca = 150
    qtd_vendas_pepsi = 130
    preco_coca = 1.50
    preco_pepsi = 1.50
    custo_loja = 2500.00


    """1. Qual foi o faturamento de Pepsi da Loja?"""
    faturamento_pepsi = qtd_vendas_pepsi * preco_pepsi
    print(f'O FATURAMENTO DA PESI FOI R$ {faturamento_pepsi:.2F}')


    """2. Qual foi o faturamento de Coca da Loja?"""
    faturamento_coca = qtd_vendas_coca * preco_coca
    print(f'O FATURAMENTO DA COCA FOI R$ {faturamento_coca:.2F}')


    """3. Qual foi o Lucro da loja?"""
    faturamento_total = faturamento_coca + faturamento_pepsi
    print(f'O FATURAMENTO DA LOJA FOI R$ {faturamento_total:.2F}')
    if faturamento_total > custo_loja:
        lucro = faturamento_total - custo_loja
        print(f'A loja teve um Lucro de {lucro} reais')
    elif faturamento_total < custo_loja:
        prejuizo = custo_loja - faturamento_total
        print(f'A loja teve um Prejuízo de {prejuizo} reais')
    else:
        print('A loja ficou no Branco, sem lucro e sem prejuizo.')


    """4. Qual foi a Margem da Loja? (Lembre-se, margem = Lucro / Faturamento). Não precisa formatar em percentual"""
    if faturamento_total > custo_loja:
        margem = lucro / faturamento_total
        print(f'A loja teve uma margem de Lucro de {margem:.2%} ')
    elif faturamento_total < custo_loja:
        margem = prejuizo / faturamento_total
        print(f'A loja teve uma margem de Prejuízo de {margem:.2%} ')
    else:
        print('A loja ficou no Branco, logo a margem é ZERO.')


"""### Parte 2 - Inputs e Strings

A maioria das empresas trabalham com um Código para cada produto que possuem. A Hashtag&Drink, por exemplo, tem mais de 1.000 produtos e possui um código para cada produto.
Ex: 
Coca -> Código: BEB1300543<br>
Pepsi -> Código: BEB1300545<br>
Vinho Primitivo Lucarelli -> Código: BAC1546001<br>
Vodka Smirnoff -> Código: BAC17675002<br>

Repare que todas as bebidas não alcóolicas tem o início do Código "BEB" e todas as bebidas alcóolicas tem o início do código "BAC".

Crie um programa de consulta de bebida que, dado um código qualquer, identifique se a bebida é alcóolica. O programa deve responder True para bebidas alcóolicas e False para bebidas não alcóolicas. Para inserir um código, use um input.

Dica: Lembre-se do comando in para strings e sempre insira os códigos com letra maiúscula para facilitar.
"""
def parte2():
    codigo = input('Verifique se a sua bebida é alcóolica (True) ou não (False) digitando seu código:')
    print('BAC' in codigo)



