# -*- coding: utf-8 -*-
"""Gabarito - Módulos e Introdução a Orientação a Objetos 07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OrjbGGIvusJeBc_tONDUSF4k41DX6YOP

# Mais edições de Gráfico com MatplotLib
"""

#importando o matplotlib
import matplotlib.pyplot as plt

"""- Usando o módulo numpy para trabalhar com números"""

#importando o módulo numpy
import numpy as np

"""### Outros tipos de Gráfico:

- Linha
"""

vendas = np.random.randint(1000, 3000, 50)
meses = np.arange(1, 51)
print(meses)

plt.plot(meses, vendas)
plt.axis([0, 50, 0, max(vendas)+200])
plt.xlabel('Meses')
plt.ylabel('Vendas')
plt.show()

"""- Editando o Gráfico de Linha"""

#mudando a linha para apenas os marcadores
plt.plot(meses, vendas, color='red')
plt.axis([0, 50, 0, max(vendas)+200])
plt.xlabel('Meses')
plt.ylabel('Vendas')
plt.show()

#editando o tamanho e a cor da linha - quais parâmetros posso editar?

"""- Dispersão"""

plt.scatter(meses, vendas)
plt.show()

"""- Barras"""

plt.bar(meses, vendas)
plt.show()

"""- Trabalhando com Múltiplos Gráficos no mesmo "Plot" -> Para melhor visualização/comparação"""

plt.figure(1, figsize=(15, 3))
plt.subplot(1, 3, 1)
plt.plot(meses, vendas, color='red')
plt.subplot(1, 3, 2)
plt.scatter(meses, vendas)
plt.subplot(1, 3, 3)
plt.bar(meses, vendas)
plt.show()